http:
  routers:
    https-redirect:
      rule: 'HostRegexp(`{any:.*}`)'
      middlewares: ['https-redirect']
      service: 'noop'
      entryPoints: ['http']

    sub-redirect:
      rule: 'Host(`ranna.zekro.de`)'
      middlewares: ['app-redirect']
      service: 'noop'
      entryPoints: ['https']
      tls:
        certresolver: le

  
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: 'https'
        permanent: true

    app-redirect:
      redirectRegex:
        regex: '.*'
        replacement: 'https://app.ranna.zekro.de'

    cors:
      headers:
        accesscontrolallowmethods:    "GET,POST"
        accesscontrolalloworiginlist: "*"
        accesscontrolallowheaders:    "*"
        accesscontrolmaxage:          "3600"
        addvaryheader:                "true"


  services:
    noop:
      loadBalancer:
        servers:
          - url: ''